{{- if .Values.ingress.enabled }}
---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-redirectscheme
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name | trunc 63 | trimSuffix "-" }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  redirectScheme:
    scheme: https
    permanent: true


---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-insecure
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name | trunc 63 | trimSuffix "-" }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  entryPoints:
    - web
  routes:
    {{- range .Values.ingress.rules }}
    - kind: Rule
      match: {{ . }}
      middlewares:
        - name: {{ $.Release.Name }}-redirectscheme
          namespace: {{ $.Release.Namespace }}
      services:
        - kind: Service
          name: {{ $.Release.Name }}
          namespace: {{ $.Release.Namespace }}
          port: 5000
    {{ end }}


---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-secure
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name | trunc 63 | trimSuffix "-" }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: letsencrypt
  routes:
    {{- range .Values.ingress.rules }}
    - kind: Rule
      match: {{ . }}
      services:
        - kind: Service
          name: {{ $.Release.Name }}
          namespace: {{ $.Release.Namespace }}
          port: 5000
    {{ end }}
{{ end }}
