apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "micro.labels" . | nindent 4 }}
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
