name: Deploy new release

on:
  repository_dispatch:
    types:
      - deploy_release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # - name: Update image
      #   uses: mikefarah/yq@master
      #   with:
      #     cmd: yq -i '.image.tag = "${{ github.event.client_payload.image_tag }}"' apps/${{ github.event.client_payload.app }}/{{ github.event.client_payload.env }}.yml

      # - name: Apply changes
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Update ${{ github.event.client_payload.app }} version in ${{ github.event.client_payload.env }}

      - name: Send notification to Telegram
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_SECRET }}
          args: |
            Update `${{ github.event.client_payload.app }}` version in `${{ github.event.client_payload.env }}` to `${{ github.event.client_payload.image_tag }}` - ${{ job.status }}
            https://argocd.clayman.pro/applications/argocd/${{ github.event.client_payload.app }}-${{ github.event.client_payload.env }}
